[package]
name = "kafrust-protocol"
version = "0.2.14"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Kafka wire protocol primitives for kafrust."
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
flate2 = { version = ">=1.0.35, <1.1", default-features = false, features = ["rust_backend"] }
lz-fear = "=0.2.0"
ruzstd = { version = "=0.8.1", default-features = false, features = ["std"] }
snap = "1.1"
