[package]
name = "kafrust"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A pure Rust Kafka client with no librdkafka or C toolchain dependency."
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
kafrust-protocol = { version = "0.0.0", path = "../kafrust-protocol" }
